"""Assemble and package exact, page-local diagnostic replacements. No GPU work."""
from pathlib import Path
import hashlib
import json
import struct
import subprocess

root = Path(__file__).resolve().parent
obj = root / 'rbplus-payload.o'
subprocess.run(['xcrun', 'clang', '-c', str(root / 'rbplus-payload.s'), '-o', str(obj)], check=True)
b = obj.read_bytes()
pos = 32
code = None
for _ in range(struct.unpack_from('<I', b, 16)[0]):
    cmd, size = struct.unpack_from('<II', b, pos)
    if cmd == 0x19:
        for i in range(struct.unpack_from('<I', b, pos + 64)[0]):
            s = pos + 72 + i * 80
            if b[s:s+16].rstrip(b'\0') == b'__text':
                length, offset = struct.unpack_from('<QI', b, s + 40)
                assert struct.unpack_from('<I', b, s + 60)[0] == 0, 'payload has relocations'
                code = b[offset:offset+length]
    pos += size
assert code is not None and len(code) == 0xd2 + 0x121
cache = Path('/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h.03')
manifest = json.loads((root / 'static-20260929/manifest.json').read_text())
output = ['// Generated by build-rbplus-payload.py; exact 25E253 cache only.']
records = []
for name, address, start, length, page in [
    ('Full', 0x26abc, 0, 0xd2, manifest['emitter_pages'][0]),
    ('Delta', 0x2bbb4, 0xd2, 0x121, manifest['emitter_pages'][1]),
]:
    with cache.open('rb') as f:
        f.seek(int(page['page_offset'], 16))
        original_page = f.read(4096)
    assert hashlib.sha256(original_page).hexdigest() == page['page_sha256']
    within = address & 4095
    assert within + length <= 4096
    original = original_page[within:within+length]
    replacement = code[start:start+length]
    for suffix, data in [('Original', original), ('Replacement', replacement), ('Page', original_page)]:
        output.append(f'static const unsigned char rb{name}{suffix}[] = {{')
        for i in range(0, len(data), 16):
            output.append('    ' + ','.join(f'0x{x:02x}' for x in data[i:i+16]) + ',')
        output.append('};')
    records.append({'name': name, 'image_offset': hex(address), 'size': length,
                    'replacement_sha256': hashlib.sha256(replacement).hexdigest(),
                    'original_sha256': hashlib.sha256(original).hexdigest()})
(root.parent.parent / 'NootedRed/rbplus-payload.h').write_text('\n'.join(output) + '\n')
(root / 'rbplus-payload.json').write_text(json.dumps(records, indent=2) + '\n')
dis = subprocess.run(['xcrun', 'llvm-objdump', '-d', str(obj)], check=True, capture_output=True, text=True)
(root / 'rbplus-payload.asm').write_text(dis.stdout)
print(json.dumps(records, indent=2))
